name: GitHub Metrics

on:
  # Schedule the workflow to run every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Trigger on pushes to main branch
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Options
          user: MustafaKemal0146
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul
          
          # Plugin: Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Plugin: Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Plugin: Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          # Plugin: Discussions
          plugin_discussions: yes
          plugin_discussions_categories: yes
          
          # Plugin: Topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars